---
- hosts: webservers 
  gather_facts: False
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: latest
	update_cache: yes
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
